In [ ]:
from skimage.measure import compare_ssim
import cv2
import numpy as np


before = cv2.imread('catskin.jpg')
after = cv2.imread('catfat.jpg')
print(before.shape)
print(after.shape)
print(before)
# Converstest imaginile in gri scale
before_gray = cv2.cvtColor(before, cv2.COLOR_BGR2GRAY)
after_gray = cv2.cvtColor(after, cv2.COLOR_BGR2GRAY)
d1 = cv2.matchShapes(before_gray,after_gray,cv2.CONTOURS_MATCH_I1,0)
print('d1',d1)
d2 = cv2.matchShapes(before_gray,after_gray,cv2.CONTOURS_MATCH_I2,0)
print('d1',d2)

d3 = cv2.matchShapes(before_gray,after_gray,cv2.CONTOURS_MATCH_I3,0)
print('d1',d3)


# gaseste similaritate SSIM 
(score, diff) = compare_ssim(before_gray, after_gray, full=True)
print("Image similarity", score)


# The diff image contine imaginea actuala a diferentelor dintre cele2 imagine
# reprezentata in range [0,1] 
#  convert array to 8-bit
# [0,255] inainte sa o folosim
diff = (diff * 255).astype("uint8")

# Threshold the difference image, + gasirea de contur
# obtinrea regiunilor celor 2 imagine 
thresh = cv2.threshold(diff, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
contours = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contours = contours[0] if len(contours) == 2 else contours[1]
moments = cv2.moments(thresh)

# huMoments = cv2.HuMoments(moments)
# print(huMoments)

# cnt = contours[-1]
# area = cv2.contourArea(cnt)
# M = cv2.moments(before_gray)
# print( M )
# cx = int(M['m10']/M['m00'])
# cy = int(M['m01']/M['m00'])
# print('cx',cx)
# cv2.circle(before_gray, (cx, cy), 15, (205, 114, 101), 1)
# cv2.imshow("Center of the Image", before_gray)



mask = np.zeros(after.shape, dtype='uint8')
print('mask', mask)
area1 = np.count_nonzero(mask)
print('area', area1)
filled_after = before.copy()
# area1 = cv2.contourArea(cnt)
# print('area countours 1', area1)
area1 = cv2.countNonZero(thresh)
print('area thresh', area1)
for c in contours:
    area = cv2.contourArea(c)
    print("area countours", area)
    if area > 300:
        x,y,w,h = cv2.boundingRect(c)
        cv2.rectangle(before, (x, y), (x + w, y + h), (50,255,50), 2)
        cv2.rectangle(after, (x, y), (x + w, y + h), (50,255,50), 2)
        cv2.drawContours(mask, [c], 0, (0,0,255), -1)
#         cv2.drawContours(filled_after, [c], 0, (0,255,0), -1)
        
area1 = np.count_nonzero(mask)
print('area mask', area1)
cv2.imshow('before', before)
cv2.imshow('after', after)
cv2.imshow('diff',diff)
cv2.imshow('mask',mask)
print("SSIM: {}".format(score))
cv2.imshow("Thresh", thresh)



# cv2.imshow('filled after',filled_after)
cv2.waitKey(0)

(400, 334, 3)
(400, 334, 3)
[[[175 160 127]
  [183 168 135]
  [188 173 140]
  ...
  [175 156 121]
  [175 156 121]
  [175 156 121]]

 [[185 171 135]
  [194 181 143]
  [198 184 148]
  ...
  [184 166 129]
  [184 166 129]
  [184 166 129]]

 [[190 178 136]
  [197 185 143]
  [203 191 149]
  ...
  [184 168 125]
  [184 168 125]
  [184 168 125]]

 ...

 [[197 215 192]
  [207 225 202]
  [210 228 205]
  ...
  [197 215 192]
  [197 215 192]
  [198 216 193]]

 [[197 215 192]
  [207 225 202]
  [210 228 205]
  ...
  [197 215 192]
  [197 215 192]
  [197 215 192]]

 [[196 214 191]
  [208 226 203]
  [210 228 205]
  ...
  [196 214 191]
  [196 214 191]
  [197 215 192]]]
d1 0.00042226529868616414
d1 0.0037598507842662166
d1 0.0012592280553286584
Image similarity 0.7559418205923875
mask [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 